apiVersion: v1
kind: Secret
metadata:
  name: ekonstat-secrets
  namespace: ekonstat
  labels:
    app.kubernetes.io/part-of: ekonstat
type: Opaque
stringData:
  database_password: "change-me"
  tunnel_token: "change-me"
